#### 这里是少部分Python代码的使用方法，对P0项目的代码理解会有帮助。

#### 项目中其它的代码部分，会在优达日上再视频讲解一部分，但不会全部都讲，希望大家能更多的通过自己的思考理解。

这部分方法对应求缺失值个数

项目中的方法也可以求，大家可以通过各种方法尝试。

In [34]:
import pandas as pd
import numpy as np

In [4]:
a = [[1,2,3,4,5],
    [6,7,8,None,10],
    [1,1,None,1,1],
    [6,6,6,6,None]]

In [5]:
a = pd.DataFrame(a,columns=['a','b','c','d','e'])
a

a  b    c    d     e
0  1  2  3.0  4.0   5.0
1  6  7  8.0  NaN  10.0
2  1  1  NaN  1.0   1.0
3  6  6  6.0  6.0   NaN

In [6]:
a.isnull().head()

a      b      c      d      e
0  False  False  False  False  False
1  False  False  False   True  False
2  False  False   True  False  False
3  False  False  False  False   True

In [7]:
a.isnull().sum()

a    0
b    0
c    1
d    1
e    1
dtype: int64

--------------------------------------------------------------------------------------------------------------------------------------------

这部分是strip()函数的使用方法：大家自己看是如何使用的。对应filter_data(data, condition):函数

In [111]:
f = '****!!!!abcdef***!!!'

In [113]:
f.strip('*!')

'abcdef'

In [8]:
g = '  ****!!!!abcdef***!!!   '

In [9]:
g.strip()

'****!!!!abcdef***!!!'

--------------------------------------------------------------------------------------------------------------------------------------------

#### 下面这部分是项目中常用的pandas数据框的使用方法，理解下面的使用方法，项目的代码就可以看懂。

In [142]:
def filter_data(data, condition):
    """
    Remove elements that do not match the condition provided.
    Takes a data list as input and returns a filtered list.
    Conditions should be a list of strings of the following format:
      '<field> <op> <value>'
    where the following operations are valid: >, <, >=, <=, ==, !=
    
    Example: ["duration < 15", "start_city == 'San Francisco'"]
    """

    # Only want to split on first two spaces separating field from operator and
    # operator from value: spaces within value should be retained.
    field, op, value = condition.split(" ", 2)
    
    # check if field is valid
    if field not in data.columns.values :
        raise Exception("'{}' is not a feature of the dataframe. Did you spell something wrong?".format(field))

    # convert value into number or strip excess quotes if string
    try:
        value = float(value)
    except:
        value = value.strip("\'\"")

    # get booleans for filtering
    if op == ">":
        matches = data[field] > value
    elif op == "<":
        matches = data[field] < value
    elif op == ">=":
        matches = data[field] >= value
    elif op == "<=":
        matches = data[field] <= value
    elif op == "==":
        matches = data[field] == value
    elif op == "!=":
        matches = data[field] != value
    else: # catch invalid operation codes
        raise Exception("Invalid comparison operator. Only >, <, >=, <=, ==, != allowed.")
    
    # filter data and outcomes
    data = data[matches].reset_index(drop = True)
    return data

In [115]:
k=pd.DataFrame([[1,2,3,4,5],
                [6,6,6,6,6],
                [8,8,8,8,8],
                [2,2,2,2,2]])

In [116]:
k

0  1  2  3  4
0  1  2  3  4  5
1  6  6  6  6  6
2  8  8  8  8  8
3  2  2  2  2  2

In [120]:
k[k[3]>4]

0  1  2  3  4
1  6  6  6  6  6
2  8  8  8  8  8

筛选后，把原有行索引丢掉，按照现在的顺序重新命名行索引。

In [119]:
k[k[3]>4].reset_index(drop=True)

0  1  2  3  4
0  6  6  6  6  6
1  8  8  8  8  8

In [148]:
def usage_stats(data, filters = [], verbose = True):
    """
    Report number of readings and average PM2.5 readings for data points that meet
    specified filtering criteria.
    """

    n_data_all = data.shape[0]

    # Apply filters to data
    for condition in filters: #["city == 'Beijing'", "season == 'Spring'"]
        data = filter_data(data, condition)#data = data[data['city'=='Beijing']]
                                           #data = data[data[season == 'Spring']]

    # Compute number of data points that met the filter criteria.
    n_data = data.shape[0]

    # Compute statistics for PM 2.5 readings.
    pm_mean = data['PM_US Post'].mean()
    pm_qtiles = data['PM_US Post'].quantile([.25, .5, .75]).as_matrix()
    
    # Report computed statistics if verbosity is set to True (default).
    if verbose:
        if filters:
            print('There are {:d} readings ({:.2f}%) matching the filter criteria.'.format(n_data, 100. * n_data / n_data_all))
        else:
            print('There are {:d} reading in the dataset.'.format(n_data))

        print('The average readings of PM 2.5 is {:.2f} ug/m^3.'.format(pm_mean))
        print('The median readings of PM 2.5 is {:.2f} ug/m^3.'.format(pm_qtiles[1]))
        print('25% of readings of PM 2.5 are smaller than {:.2f} ug/m^3.'.format(pm_qtiles[0]))
        print('25% of readings of PM 2.5 are larger than {:.2f} ug/m^3.'.format(pm_qtiles[2]))
        seaborn.boxplot(data['PM_US Post'], showfliers=False)
        plt.title('Boxplot of PM 2.5 of filtered data')
        plt.xlabel('PM_US Post (ug/m^3)')

    # Return three-number summary
    return data

In [11]:
if []:
    print('a')
else:
    print('b')

b


In [12]:
if True:
    print('a')

a


In [13]:
for i in []:
    print(i)

--------------------------------------------------------------------------------------------------------------------------------------------

In [26]:
a = pd.DataFrame([[1,1,1,1,1],
                 [2,2,2,2,2],
                 [3,3,3,3,3],
                 [4,4,4,4,4],
                 [5,5,5,5,5]],columns=['a','b','c','d','e'])

In [27]:
a

a  b  c  d  e
0  1  1  1  1  1
1  2  2  2  2  2
2  3  3  3  3  3
3  4  4  4  4  4
4  5  5  5  5  5

求每一列的百分位数

In [28]:
a.quantile([.25, .5, .75])

a    b    c    d    e
0.25  2.0  2.0  2.0  2.0  2.0
0.50  3.0  3.0  3.0  3.0  3.0
0.75  4.0  4.0  4.0  4.0  4.0

返回的是一个numpy数组而不是numpy矩阵

In [29]:
a.quantile([.25, .5, .75]).as_matrix()

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [30]:
b = a['e'].quantile([.25, .5, .75])

In [31]:
type(b)

pandas.core.series.Series

比较数组和序列的区别：数组不带标签，序列是带有标签的数组。

In [32]:
b

0.25    2.0
0.50    3.0
0.75    4.0
Name: e, dtype: float64

In [35]:
np.array(b)

array([2., 3., 4.])

----------------------------------------------------------------------------------------------------------------------------------------------

.as_matrix()返回的是数组而不是矩阵

In [36]:
a['e'].quantile([.25, .5, .75]).as_matrix()

array([2., 3., 4.])

In [37]:
a.as_matrix()

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]], dtype=int64)

In [38]:
a.shape

(5, 5)

In [39]:
a.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [40]:
a.index

RangeIndex(start=0, stop=5, step=1)

In [41]:
a.columns.values

array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [42]:
a.index.values

array([0, 1, 2, 3, 4], dtype=int64)

In [43]:
a[4]='city'

In [44]:
a

a  b  c  d  e     4
0  1  1  1  1  1  city
1  2  2  2  2  2  city
2  3  3  3  3  3  city
3  4  4  4  4  4  city
4  5  5  5  5  5  city

-------------------------------------------------------------------------------------------------------------------------------------------

In [45]:
b = a

In [46]:
a.append(b)

a  b  c  d  e     4
0  1  1  1  1  1  city
1  2  2  2  2  2  city
2  3  3  3  3  3  city
3  4  4  4  4  4  city
4  5  5  5  5  5  city
0  1  1  1  1  1  city
1  2  2  2  2  2  city
2  3  3  3  3  3  city
3  4  4  4  4  4  city
4  5  5  5  5  5  city

In [47]:
pd.concat([a,b],axis=1)

a  b  c  d  e     4  a  b  c  d  e     4
0  1  1  1  1  1  city  1  1  1  1  1  city
1  2  2  2  2  2  city  2  2  2  2  2  city
2  3  3  3  3  3  city  3  3  3  3  3  city
3  4  4  4  4  4  city  4  4  4  4  4  city
4  5  5  5  5  5  city  5  5  5  5  5  city

In [48]:
pd.concat([a,b],axis=0)

a  b  c  d  e     4
0  1  1  1  1  1  city
1  2  2  2  2  2  city
2  3  3  3  3  3  city
3  4  4  4  4  4  city
4  5  5  5  5  5  city
0  1  1  1  1  1  city
1  2  2  2  2  2  city
2  3  3  3  3  3  city
3  4  4  4  4  4  city
4  5  5  5  5  5  city

In [49]:
a='99999'
b=66666

In [50]:
"12345%s%d"%(a,b)

'123459999966666'

In [51]:
"12345{},{}".format(a,b)

'1234599999,66666'

如果不写分隔次数，则每次见到，都分隔一次

In [52]:
a = '123,345,678'

In [53]:
a.split(',')

['123', '345', '678']

In [54]:
a.split(',',1)

['123', '345,678']